name: SilkSpawners
main: me.exphc.SilkSpawners.SilkSpawners
version: 1.3
url: http://dev.bukkit.org/server-mods/silkspawners/
description: pick up and move monster spawners using silk touch
softdepend: [Spout]
commands:
    silkspawners:
        aliases: [silkspawner, ss, spawner]
        description: Change or view the monster spawner creature type
        usage: /<command> [creature]|[creature]egg|all
permissions:
    silkspawners.*:
        children:
            silkspawners.info: true
            silkspawners.silkdrop: true
            silkspawners.destroydrop: true
            silkspawners.viewtype: true
            silkspawners.changetype: true
            silkspawners.changetypewithegg: true
            silkspawners.freeitem: true
        default: false
    silkspawners.info:
        description: Allows you to see informative messages about the spawners as you place and break them
        default: false
    silkspawners.silkdrop:
        description: Allows you to use silk touch to acquire mob spawner items
        default: false
    silkspawners.destroydrop:
        description: Allows you to destroy mob spawners to acquire mob spawn eggs / iron bars / XP (as configured)
        default: false
    silkspawners.viewtype:
        description: Allows you to view the spawner type using /spawner
        default: false
    silkspawners.changetype:
        description: Allows you to change the spawner type using /spawner [creature]
        default: false
    silkspawners.changetypewithegg:
        description: Allows you to change the spawner type by left-clicking with a spawn egg
        default: false
    silkspawners.freeitem:
        description: Allows you to get spawner items in your hand for free using /spawner [creature]
        default: false
    silkspawners.freeitemegg:
        description: Allows you to get spawn eggs in your hand for free using /spawner [creature]egg
        default: false
softdepend:
    - WorldGuard
